<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Eccube\Repository\OAuth2;

use Eccube\Entity\OAuth2\AuthorizationCode;
use Eccube\Repository\AbstractRepository;
use OAuth2\Storage\AuthorizationCodeInterface;
use OAuth2\OpenID\Storage\AuthorizationCodeInterface as OpenIDAuthorizationCodeInterface;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * AuthorizationCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @author Kentaro Ohkouchi
 *
 * @see http://bshaffer.github.io/oauth2-server-php-docs/cookbook/doctrine2/
 */
class AuthorizationCodeRepository extends AbstractRepository implements AuthorizationCodeInterface, OpenIDAuthorizationCodeInterface
{
    /**
     * ClientRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, AuthorizationCode::class);
    }

    /**
     * コードを指定して Authorization code のフィールドの配列を取得します.
     *
     * @param string $code コードの文字列
     *
     * @return array Authorization code のフィールドの配列
     */
    public function getAuthorizationCode($code)
    {
        $authCode = $this->findOneBy(['code' => $code]);
        if ($authCode && $authCode->getExpires()->getTimestamp() >= time()) {
            $authCode = $authCode->toArray();
            if (is_object($authCode['client'])) {
                $authCode['client_id'] = $authCode['client']->getClientIdentifier();
            }
            if (is_object($authCode['user'])) {
                $authCode['user_id'] = $authCode['user']->getId();
            }
            $authCode['expires'] = $authCode['expires']->getTimestamp();
        }

        return $authCode;
    }

    /**
     * AuthorizatoinCode を生成して保存します.
     *
     * 第3引数の $user_id は、 UserInfo::sub の文字列が渡ってくることに注意します.
     *
     * @param string $code コードの文字列
     * @param string $clientIdentifier client_id 文字列
     * @param string $user_id UserInfo::sub
     * @param string $redirectUri redirect_uri
     * @param integer $expires 有効期限の UNIX タイムスタンプ
     * @param string $scope 認可された scope. スペース区切りで複数指定可能
     * @param string $id_token OpenID Connect ID token
     */
    public function setAuthorizationCode($code, $clientIdentifier, $user_id, $redirectUri, $expires, $scope = null, $id_token = null)
    {
        $client = $this->_em->getRepository('Eccube\Entity\OAuth2\Client')
            ->findOneBy(
                ['client_identifier' => $clientIdentifier]
            );
        $user = $this->_em->getRepository('Eccube\Entity\OAuth2\OpenID\UserInfo')
            ->findOneBy(
                ['sub' => $user_id]
            );
        $AuthorizationCode = $this->_em->getRepository('Eccube\Entity\OAuth2\AuthorizationCode')
            ->findOneBy(
                ['code' => $code]
            );

        $now = new \DateTime();
        if ($AuthorizationCode) {
            $AuthorizationCode->setPropertiesFromArray(
                [
                    'code' => $code,
                    'client' => $client,
                    'user' => $user,
                    'redirect_uri' => $redirectUri,
                    'expires' => $now->setTimestamp($expires),
                    'scope' => $scope,
                    'id_token' => $id_token,
                ]
            );
        } else {
            $AuthorizationCode = new \Eccube\Entity\OAuth2\AuthorizationCode();
            $AuthorizationCode->setPropertiesFromArray(
                [
                    'code' => $code,
                    'client' => $client,
                    'user' => $user,
                    'redirect_uri' => $redirectUri,
                    'expires' => $now->setTimestamp($expires),
                    'scope' => $scope,
                    'id_token' => $id_token,
                ]
            );
            $this->_em->persist($AuthorizationCode);
        }

        $this->_em->flush($AuthorizationCode);
    }

    /**
     * 期限切れとなった AuthorizationCode を削除します.
     *
     * @param string $code コードの文字列
     */
    public function expireAuthorizationCode($code)
    {
        $authCode = $this->findOneBy(['code' => $code]);
        if ($authCode && $authCode->getExpires()->getTimestamp() <= time()) {
            $this->_em->remove($authCode);
            $this->_em->flush($authCode);
        }
    }
}
